#!/usr/bin/env python3
"""Ironsights (`_aim`) model variants for the Guns resource pack.

Crouch-aiming (v0.9.0) swaps a held gun's custom_model_data string from
`<model>` to `<model>_aim` while the player sneaks. This script writes, for
every base gun model it knows about:

  assets/guns/models/item/<model>_aim.json
      identical textures/elements (via "parent": the base model), but with a
      display block whose firstperson transforms center the gun toward the
      middle of the screen and pull it slightly closer - the ironsights feel.
      Every other display context (thirdperson, gui, ground, fixed) is copied
      from the base model unchanged, so only the holder's own view changes.

and adds a `<model>_aim` dispatch case to assets/minecraft/items/crossbow.json,
keeping the existing cases and the vanilla charged/pulling fallback intact.

No textures are needed - the _aim models reuse the base models' textures.

Run from the repo root:  python3 tools/gen_aim_models.py
"""
import json
import os

GUN_MODELS = ["gun_pistol", "gun_rifle", "gun_venom"]

# Ironsights first-person transform: no yaw so the barrel lines up with the
# view axis, translated to the screen center and slightly closer. Scale is
# kept from each base model so the gun does not change size while aiming.
AIM_FP_ROTATION = [0, 0, 0]
AIM_FP_TRANSLATION = [-4.5, 1.5, -2]

root = os.path.join(os.path.dirname(__file__), "..", "resource-pack", "assets")
models_dir = os.path.join(root, "guns", "models", "item")

for model in GUN_MODELS:
    base_path = os.path.join(models_dir, model + ".json")
    with open(base_path) as f:
        base = json.load(f)

    display = dict(base.get("display", {}))
    fp_scale = display.get("firstperson_righthand", {}).get("scale", [1, 1, 1])
    display["firstperson_righthand"] = {
        "rotation": AIM_FP_ROTATION,
        "translation": AIM_FP_TRANSLATION,
        "scale": fp_scale,
    }
    # mirrored for the left hand: same centering, x flipped
    display["firstperson_lefthand"] = {
        "rotation": AIM_FP_ROTATION,
        "translation": [-AIM_FP_TRANSLATION[0]] + AIM_FP_TRANSLATION[1:],
        "scale": fp_scale,
    }

    aim = {
        "credit": f"Ironsights variant of {model} - generated by tools/gen_aim_models.py",
        "parent": f"guns:item/{model}",
        "display": display,
    }
    aim_path = os.path.join(models_dir, model + "_aim.json")
    with open(aim_path, "w") as f:
        json.dump(aim, f, indent=2)
        f.write("\n")
    print(aim_path)

# splice the _aim cases into the crossbow dispatch (idempotent: existing
# _aim cases are replaced, everything else - vanilla fallback included -
# is left exactly as found)
dispatch_path = os.path.join(root, "minecraft", "items", "crossbow.json")
with open(dispatch_path) as f:
    dispatch = json.load(f)

cases = dispatch["model"]["cases"]
wanted = {m + "_aim" for m in GUN_MODELS}
cases[:] = [c for c in cases if c.get("when") not in wanted]
for model in GUN_MODELS:
    cases.append({
        "when": model + "_aim",
        "model": {"type": "minecraft:model", "model": f"guns:item/{model}_aim"},
    })

with open(dispatch_path, "w") as f:
    json.dump(dispatch, f, indent=2)
    f.write("\n")
print(dispatch_path)
print("aim models + crossbow dispatch done")
