#!/usr/bin/env python3
"""Empty-magazine (`_emptymag`) model variants for the Guns resource pack.

Reloading (v0.10.0) drops a gun's charged crossbow projectile the moment it runs
dry, so holding right-click plays the crossbow's own charging animation as the
reload. While the gun is empty its custom_model_data string is swapped from
`<model>` to `<model>_emptymag`, giving the reload its own model state.

This script writes, for every base gun model it knows about:

  assets/guns/models/item/<model>_emptymag.json
      by default a thin variant that just inherits the base model (via "parent"),
      so the gun still renders while you author the real empty-mag look (mag
      removed / bolt back / etc.). Replace the texture or elements here to make
      the empty state visually distinct - nothing else needs to change.

and adds a `<model>_emptymag` dispatch case to
assets/minecraft/items/crossbow.json, keeping the existing cases and the vanilla
charged/pulling fallback intact.

Run from the repo root:  python3 tools/gen_emptymag_models.py
"""
import json
import os

GUN_MODELS = ["gun_pistol", "gun_rifle", "gun_venom"]

root = os.path.join(os.path.dirname(__file__), "..", "resource-pack", "assets")
models_dir = os.path.join(root, "guns", "models", "item")

for model in GUN_MODELS:
    empty = {
        "credit": f"Empty-magazine variant of {model} - generated by "
                  f"tools/gen_emptymag_models.py (retexture me for the empty look)",
        "parent": f"guns:item/{model}",
    }
    empty_path = os.path.join(models_dir, model + "_emptymag.json")
    # do not clobber a hand-authored empty-mag model if one already exists
    if os.path.exists(empty_path):
        with open(empty_path) as f:
            existing = json.load(f)
        if "generated by" not in existing.get("credit", ""):
            print(f"keep (hand-authored): {empty_path}")
            continue
    with open(empty_path, "w") as f:
        json.dump(empty, f, indent=2)
        f.write("\n")
    print(empty_path)

# splice the _emptymag cases into the crossbow dispatch (idempotent)
dispatch_path = os.path.join(root, "minecraft", "items", "crossbow.json")
with open(dispatch_path) as f:
    dispatch = json.load(f)

cases = dispatch["model"]["cases"]
wanted = {m + "_emptymag" for m in GUN_MODELS}
cases[:] = [c for c in cases if c.get("when") not in wanted]
for model in GUN_MODELS:
    cases.append({
        "when": model + "_emptymag",
        "model": {"type": "minecraft:model", "model": f"guns:item/{model}_emptymag"},
    })

with open(dispatch_path, "w") as f:
    json.dump(dispatch, f, indent=2)
    f.write("\n")
print(dispatch_path)
print("emptymag models + crossbow dispatch done")
